<!-- FA Questions Text -->
<div id="js__scroll-to-section" class="g-container--md g-padding-y-80--xs g-padding-y-125--sm">
	<h2 id="textHead" class="g-font-size-32--xs g-font-size-36--md g-text-center--xs g-margin-b-80--xs">CİN, ŞEYTAN NEDİR? MUSALLAT VE ETKİLERİ NELERDİR?</h2>

	<div class="g-text-left--xs">
		<div>
			
			<p align="justify">Gaybi (görünmeyen) varlık olan cin hakkında en doğru bilgi, yine bu alemden insanlara gönderilen kutsal kitaplar ve bunları  tebliğ eden görevli peygamberler tarafından  bildirilmiştir. Bunların dışında söylenenler gerçek olmayan hurafelerdir. Bu kitaplardan biri olan ve Hz Muhammed'e gönderilmiş Kur'an-ı Kerim, tahrif edilmediğinden (bozulmadığından) en doğru bilgiler buradan elde edilir. Tevrat ve İncil insanlar tarafından tahrif edildiğinden, oradaki bilgiler tam anlamıyla Yüce Allah'ın bildirdiği şekilde değildir ve güvenilemez. Ayrıca Hz Muhammed'in hadislerinde de bu konuyla ilgili bilgiler mevcuttur. Dolayısı ile gayb aleminde bulunan varlıklar ve özellikleri ile ilgili doğru bilgileri sadece İslam dininden elde edebiliriz. Diğer kaynaklar ve hurafeler bizi yanıltır ve yanlış insanlara ve yöntemlere yönelmemize neden  olur. Bu da, bize faydadan ziyade zarar verir. </p>
				<p align="justify">Aşağıda cinler, şeytanların özellikleri, fiilleri ve insanlar ile olan ilişkilerini, daha ziyade misyonlarını bildiren Kur'an ayetleri bize yeterince bilgi vermektedir. Onlar da insanlar gibi kulluk imtihanına mükellef tutulmakla birlikte, aynen insanlarda da olduğu gibi şeytan denilen inançsızları Allah'a isyan etmiş ve İslama karşı savaş açarak, insanların özellikle iman etmelerini önlemek için ruhlarına musallat olarak, insanları nefsi ve şehevi bir yaşam tarzına alıştırıp, dinin emirlerine aykırı bir hayata sürmeleri ve sonunda inkar eden bir insan olarak cehennemlik olmaları için faaliyet gösterirler. Bunu gerçekleştirirken en etkili stratejileri insanların ruhsal dengesini bozmak ve hastalandırmaktır. Böyle bir insanın çok kolay yönetir, yönlendirir ve yanlış davranışlar telkin ederek hayatlarını alt üst ederler.
				</p><p align="justify">ZARİAT SURESİ 56: Ben cinleri ve insanları ancak bana ibadet etsinler diye yarattım."
					<p>RAHMAN SURESİ 14: Allah insanı, pişmiş bir çamura benzeyen bir balçıktan yarattı. 15: Cinleride halis ateşten yarattı.
					HİCR 27: Cinleri de daha önce insan vücudunun gözeneklerinden geçebilen güçlü bir ateşten yarattık.</p>
					<p>CİNN SURESİ 1: De ki: Hakikat birtakım cinlerin Kur'an dinleyip de şöyle dedikleri bana vahyedildi. Şüphesiz biz, hayret verici bir Kur'an dinledik. 2: O Kur'an hidayete erdiriyor, biz de ona iman ettik. Rabbimize hiçbirşeyi ortak koşmayacağız. 3: Doğrusu, Rabbimizin şanı çok yüksektir. Ne bir arkadaş edinmiştir, ne de bir çocuk. 4: Meğer bizim beyinsiz İblis, Allah hakkında saçma şeyler söylüyormuş.</p>
					<p>HACC 4: O şeytan ki, hakkında şöyle hüküm verilmiştir: Şüphesiz kim onu dost edinirse, o muhakkak onu  saptırır ve doğruca cehennem azabına götürür.</p>
					<p>ARAF 27: Ey Ademoğulları, şeytan ana babanızı, çirkin yerlerini onlara göstermek için elbiselerini soyarak cennetten çıkardığı gibi, sizi de şaşırtıp bir belaya düşürmesin! Çünkü o ve kabilesi, sizin onları göremeyeceğiniz yerden sizi görürler. Biz şeytanları, inanmayanların dostu yaptık.</p>
					<p>BAKARA 168: Ey insanlar! Bütün yeryüzündeki nimetlerimden helal olmak, temiz olmak şartıyla yiyin. Fakat şeytanın adımlarına uymayın. Çünkü o size belli bir düşmandır. <169: O (şeytan) size hep çirkin ve murdar işleri emreder. Allah'a karşı bilmediğiniz şeyleri söylemenizi ister. 208: Ey iman edenler! Hepiniz barış ve selamete girin de şeytanın adımlarına uymayın. Çünkü o sizin aranızı açan belli bir düşmandır. 268: Şeytan sizi fakirlikle korkutup çirkin şeylere teşvik eder. Allah da lütfundan ve bağışlamasından birtakım vaatlerde bulunuyor. Allah'ın lütfu geniştir. O her şeyi bilendir.</p>
					<p>NUR SURESİ 24: Ey iman edenler! Şeytanın adımlarını takip etmeyin. Kim şeytanın adımlarını takip ederse, şunu bilsin ki o, edepsizlikleri ve kötülüğü emreder. Eğer üstünüzde Allah'ın lütuf ve merhameti olmasaydı, içinizden hiçbir kimse temize çıkmazdı. Fakat Allah dilediğini arındırır. Allah işitir ve bilir.</p>
					<p>FATIR SURESİ 5: Ey insanlar! Haberiniz olsun ki, Allah'ın vaadi muhakkak haktır. Sakın bu dünya hayatı sizi aldatmasın, sakın o aldatıcı şeytan sizi, Allah hakkında da aldatmasın. 6: Çünkü şeytan size düşmandır. Siz de onu düşman tutun. O etrafına toplanan taraftarlarını ancak cehennemliklerden olsunlar diye davet eder. 38: Şüphe yok ki Allah, göklerin ve yerin gaybını bilir. Elbette o, sinelerin içinde olanları da bilir.</p>
					<p>MAİDE SURESİ 90: Ey iman edenler! İçki, kumar, dikili taşlar (putlar) ve fal okları şeytan işi birer pisliktir. Bunlardan kaçının ki, kurtuluşa eresiniz. 91: Şeytan, içki ve kumar ile sizin aranıza düşmanlık ve kin sokmak ve sizi Allah'ı anmaktan ve namazdan alıkoymak ister. Artık bunlardan vazgeçtiniz değil mi?</p>
					<p>NİSA 117: Onlar (kafirler), Allah'ı bırakırlar da, yalnız dişilere taparlar. Böylece ancak inatçı şeytana tapmış olurlar. 118: Allah o şeytana lanet etti. Ve o da: "Elbette senin kullarından belirli bir pay alacağım, onları mutlaka saptıracağım, onları boş kuruntularla oyalayacağım." 119: "Onlara emredeceğim de hayvanların kulaklarını yaracaklar, onlara emredeceğim de Allah'ın yaratışını değiştirecekler" (genler ile oynama, biyolojik yapıyı değiştirme) dedi. Kim Allah'ı bırakıp da şeytanı dost edinirse, şüphesiz o, apaçık bir ziyana uğramış olur. 120: Şeytan onlara vaad eder ve onları boş umutlar ile oyalar. Oysa şeytanın onlara vaadi, aldatmadan başka birşey değildir.</p>
					<p>ZUHRUF SURESİ 36: Her kim Rahman olan Allah'ın zikrinden yüz çevirirse biz ona bir şeytan musallat ederiz. Artık o şeytan onun yakın dostudur. 37: Şüphesiz ki bu şeytanlar onları yoldan çıkarırlar. Onlar da kendilerinin doğru yolda olduklarını sanırlar. 62: Sakın şeytan sizi doğru yoldan alıkoymasın. Gerçekten o sizin için apaçık bir düşmandır.</p>
					<p>MUHAMMED SURESİ 25: Gerçekten doğru yol kendilerine açıkça belli olduktan sonra gerisin geri küfre dönenlere şeytan, kötülüklerini güzel göstermiş ve onları uzun emellere düşürmüştür.</p>
					<p>ŞUARA 221: Şeytanların kime ineceğini size haber vereyim mi? 222: Onlar, günaha ve iftiraya düşkün olan herkesin üzerine inerler. 223: Onlar, şeytanlara kulak verirler, onların çoğu yalancıdır.</p>
					<p>İBRAHİM SURESİ 22: İş bitince şeytan onlara şöyle diyecek: "Şüphesiz ki, Allah size gerçek olanı vaat etti, ben de size vaat ettim ama sonra caydım! Zaten benim size karşı bir gücüm yoktu. Ancak ben sizi küfür ve isyana çağırdım, siz de geldiniz. O halde beni kınamayın, kendinizi kınayın! Ne ben sizi kurtarabilirim, ne de siz beni kurtarabilirsiniz! Ben, önceden beni Allah'a ortak koşmanızı da kabul etmemiştim". Doğrusu zalimler için acı bir azap vardır!</p>
					<p>YASİN 60: "Ey Ademoğulları! Şeytana tapmayın, o size apaçık düşmandır diye size and vermedim mi?" Çünkü o sizin apaçık düşmanınızdır. 61: Bana kulluk edin doğru yol budur. 62: Böyle iken o sizden birçok nesilleri yoldan çıkardı. Ya o zaman düşünmüyor muydunuz? 63: İşte bu size vaat edilen cehennemdir.
					NAHL 99: Şüphesiz ki, iman edip te Rablerine tevekkül edenler üzerinde o şeytanın hiçbir nüfuzu yoktur. 100: Şeytanın nüfuzu, ancak onu dost edinenlere ve Allah'a ortak koşanlaradır.</p>
					<p>FUSSİLET 30: "Rabbimiz Allah'tır deyip, sonra da doğrulukta devam edenlere gelince, onların üzerine melekler iner ve derler ki: "Korkmayın, üzülmeyin, size vaat edilen cennetle sevinin" 31: "Biz dünya hayatında da, ahirette de sizin dostlarınızız. Cennette sizin için canınızın çektiği ve istediğiniz herşey vardır"36: Eğer şeytandan gelecek kötü bir düşünce seni dürtecek olursa hemen Allah'a sığın. Çünkü o herşeyi işitir ve bilir.</p>
					<p>ARAF 200: Eğer şeytandan bir vesvese, bir kışkırtma gelirse hemen Allah'a sığın. Muhakkak ki, Allah hakkıyla işiten, ve kemaliyle bilendir. 201: Allah'tan korkanlar, kendilerine şeytandan bir vesvese iliştiği zaman, durup düşünürler de derhal kendi basiretlerine sahip olurlar. 202: Şeytanların kardeşlerine gelince, onlar öbürlerini sapıklığa sürüklerler, sonra da yakalarını bırakmazlar.</p>
					<p>MÜCADELE SURESİ 10: Gizli konuşmalar şeytandandır. Bu iman edenleri üzmek içindir. Oysa şeytan, Allah'ın izni olmadıkça müminlere hiçbir zarar veremez. Müminler Allah'a dayanıp güvensinler.</p>
					<p>MÜMİNUN SURESİ 97: De ki: Rabbim! şeytanların kışkırtmalarından sana sığınırım!98: Onların yanımda bulunmalarında da sana sığınırım.</p>
					<p>ENAM SURESİ 17: Allah sana bir zarar dokundurursa, onu kendisinden başka giderecek yoktur. Eğer sana bir hayır dokundursa, kuşkusuz O, herşeyi yapabilendir. 18: O, kullarının üstünde tam hakimdir. O, hüküm ve hikmet sahibidir, herşeyden haberdardır. 61: O, kullarının üzerinde hükümranlığını sürdürür ve size koruyucular gönderir, sonunda sizden birine ölüm geldiği vakit elçilerimiz, hiç eksiklik yapmadan, onun canını alırlar.</p>
					<p>RAD SURESİ 11: Her insan için önünden ve arkasından takip edenler vardır. Allah'ın emriyle onu gözetirler...</p>
					<p>SECDE SURESİ 41: Ey iman edenler! Allah'ı çokça anın. 42: O'nu sabah akşam tespih edin. 43: Sizleri karanlıklardan aydınlığa çıkarmak için melekleri ile birlikte üzerinize rahmet ve bereket indiren O'dur ve O, müminlere çok merhametlidir.</p>
				</p><p align="justify">Yukarıdaki ayetleri yorumladığımızda şunları elde ederiz. Yüce Allah Kur'an'da şöyle buyurmuştur; " Cinleri de daha önce insan vücudunun gözeneklerinden geçebilen güçlü bir ateşten yarattık. (Hicr/27)" Cin Allah'ın hava ile karışık alevli ateşten yaratmış olduğu, insanların gözle göremediği bir varlıktır. Gözüyle görmesede, cinin varlığına iman etmesi, müslümana Kur'anda bildirilen gaybi bilgilerdendir ve Allah'ın Kur'an-ı Kerim ve Hz Muhammed ile bildirdiği herşeye şüphesiz iman etmek halis bir İslam inancının gereğidir. Bunlardan bazısını kabullenip bazısını inkar etmek küfürdür. Haşa Allah'a yalan isnad edilmiş olur. İnsanın dinden çıkarır. Kur-an'ı Kerim'de bulunan on surede geçen kırk kadar ayette cinlerden bahsedilmiştir. Müslüman hiç şüphe etmeden cinin varlığına iman etmelidir. Cin ile ilgili hikaye ve inançları, Kur'ana ve sünnete uygunluğu ile kabul etmek, uygun olmayan hurafelere inanmamak gerekir.
				</p><p align="justify">Cinler de insanlar gibi akıl, irade ve nefis sahibi canlılardır. Yer, içer evlenip çoğalırlar. İnsanlara göre daha uzun yaşarlar ve ecelleri geldiğinde ölürler. Cinler göremediğimiz, onların bizi gördüğü gizli (görünmeyen) yaratıklardır. Yeryüzünde yaşarlar fakat farklı bir boyuttadırlar. Aynı mekanları kullanırız. Bizim gibi organik bedenleri yoktur, enerji bedenli holografik canlılardır. Cinler çeşitli suretlere girmeye, zor işleri yapmaya güçleri ve yetenekleri olan varlıklardır. Kısa zamanda bir yerden başka bir yere gidebilme özellikleri vardır. Cinlerin enerji yapılı olması nedeniyle, insan bedenine girebilme, nüfuz edebilme özellikleri vardır. Cinlerin insan bedenine girmesine "Cin dokunması veya çarpması" denilmektedir. İnsan bedenine girdiklerinde bizim ruhsal enerjimize olumsuz tesirde bulunurlar. Hem ruhumuzun, hem de beyin ve sinir sistemimizin sağlığını bozarlar. 
				</p><p align="justify">Allah'a ilk isyan eden varlık olarak bilinen İblis de cin taifesindendir. Cinlerde aynen insanlar gibi, Allah'a iman ve itaat etmekle mükellef kılınmıştır. Hz. Muhammed'in (S.A.V) peygamberliğine iman edip, Kur'an-Kerim'in emirlerine uymaları teklif edilmiştir. Bu nedenle cinlerin iman eden müslüman taifesi olduğu gibi, iman etmeyen, isyan eden ve İblise itaat eden kafir taifeside vardır. Bu kafir taifesindeki cinlere Şeytan denilir. Farklı güç ve yeteneklerine bağlı olarak şeytanlara ammar, ervah, şeytan, ifrit gibi isimler de verilir. 
				</p><p align="justify">Cinler insanlara daha ziyade ruhsal yönden tesir ederler. Başlangıçta bizimle rüyalarımızda iletişime geçerler. Özellikle rüyalarımızdaki yaşanılan korkulu, sıkıntılı ve koşullandırıcı senaryoları  hem duygusal değişime uğratmak hem de kişilik özelliklerimize karıştırmak istedikleri bazı kötü-yanlış alışkanlık ve davranışları da kazandırmak için kurgularlar. Özellikle küçük çocukların kişiliklerini kendi iradeleri doğrultusunda oluşturmak için onlar ile daha fazla uğraşırlar. Uykudan çığlık atarak uyanan ve ağlayan çocukları rüyalarında korkuturlar. Aniden huyları ve alışkanlıkları değişen çocukların bu durumlarının arka planında şeytanların onlara olan olumsuz etkileri vardır. Cinlerin inançsız kafir olan ve şeytan denilen kesimi insanların düşmanı olduğundan, özellikle ruhsal dengenin bozulması ve psikolojik rahatsızlıkların ortaya çıkması için insanlarda düşünsel, duygusal yükleme (vesvese, fit) faaliyetlerini gerçekleştirirler. Musallat ile insanların bilinçlerini ele geçirmeye ve benliklerini pasifleştirerek onları kendi benlikleri ile yönetmeye başlarlar. İnsanları gerçek hayattan kopararak delirtirler. Bu durumdaki insanlara görünür ve onlar ile konuşurlar.
				</p><p align="justify">Müslüman cinler kimseye zarar vermezler. İnsanlar ile temas kurmazlar, hizmet etmezler. Burada bir konuyu da belirtmek gerekir. Bazı istismarcı cinci hocalar veya şifacılar, müslüman cinlerden hadimlerinin olduğunu söyleyerek bunlarla musallatı ortadan kaldırdıklarını iddia ederler. Bunlar tamamen yalancıdırlar. Çünkü; Kur'an da ve sünnette bu iddiayı destekleyen hiçbir ayet ve hadis yoktur. Bu iddiada bulunanlar kendilerini ehliyetli gösterip, maddi kazanç sağlamak için müslüman cin hadimlerinin olduğu yalanını yayarlar. İnternette cin çıkarma seanslarında önceden ayarladıkları oyuncularla gerçek olmayan senaryoları uygulayarak insanları aldatırlar. Ya da kendileri ile işbirliği yapanlar şeytanlar varsa da, işbirliği yaptıkları cinler bu saflara suret-i haktan görünen ve onları aldatan kafir cinlerdir. Fakat işbirliği yaptığı insana gerçek yüzünü ve niyetini göstermez.  Bu cahil veya çıkarcı insanlar vesilesiyle şifa verme adına gelen hastalara musallat olurlar veya onların hastalıklarını artırırlar. Dolayısı ile sadece kafir cinler kötülük yapmak amacıyla ilgili insanla işbirliği yapar, müslüman cinler hiçbir şekilde bir insanla işbirliği yapmaz. 
				</p><p align="justify">Ancak, inançlı olmayan kafir cinler her zaman değil, kimi zaman insanlara zarar verebilirler. Bu zarar verme cinlerin insan bedenine girebilme özellikleri ile ilgilidir. Cinler, gözle görülmeyen enerji yapılı şeffaf bir varlıktır. Röntgen ışınları veya radyasyon gibi kolaylıkla insan bedenine nüfuz eder ve doğrudan beyine yönelir. Bu suretle özellikle insan beynine, sinir sistemine ve diğer organlara etki ederler.
				</p><p align="justify">Cinin insan bedenine girmesine cinin dokunması veya çarpması denir (Bakara 275, Kamer 9). Bunu kafir cinler yaparlar. Cinlerin insanları çarpmasının sebebi şöyledir; ayet ve hadislerde izah edildiği üzere, insanlar ile cinler dünyada birlikte yaşarlar. Aynı mekanları kullanabilirler. Bu yaşantı esnasında  insanlar, göremedikleri için bilmeden cinleri rahatsız edecek davranışlarda bulunur. Bu da,  cinlerin insanlara öfkelenmelerine ve kin tutmalarına neden olur. Zaten cinler insanlara göre daha çirkin yaratıklar olduğundan, insanların cinlerden sonra eşref-i mahlukat (yaratıkların en güzeli) olarak yaratılması cinlerin kıskançlığına yol açmıştır. Çünkü onlarda da nefis vardır. Aslında işin temelinde İblisin (cinlerin atası) Hz. Adem'e secde etmeyip Allah'a isyanı yatar (Araf 11-27). Bu yüzden Allah'ın huzurundan kovulan İblis, Allah'tan kıyamete kadar süre istemiş, ve bu süre boyunca Hz Adem'in soyu ile uğraşıp onları doğru yoldan çıkararak, kendisi ile birlikte cehennemlik olmaları için çalışacağına yemin etmiştir. Cinlerin kafir taifesi olan şeytanlar İblisten emir aldıkları için, bu amaç doğrultusunda insanlara temas ederek ruhsal, psikolojik hastalıklara ve neticesinde davranış bozukluğuna yol açarlar. Şeytanlar uyumaz ve sürekli insanlarla uğraşırlar.
				</p><p align="justify">Yine Kur'an-ı Kerim'de Allah: " O (şeytan) ve kabilesi sizin onları göremeyeceğiniz yerden onlar sizi görürler " buyurmaktadır. Yani, insan onları duyu organları ile algılayamadığı için onlardan kolayca korunamaz ve saldırılarının hedefi olurlar. <u>Fakat şeytanlar Kur'an-ı Kerim'in ifadesiyle Allah'a sığınan imanlı ve ibadetli insanlardan ziyade, Allah'a şirk koşan veya inkar eden, Allah'ın zikrini terketmiş, heva ve hevesini ön plana çıkararak nefsin kötü arzularına teslim olmuş, hayatında helal-haram, iyi-kötü ayırımına dikkat etmeden yaşayan insanlara daha fazla saldırır, onların ruh ve bedenlerini ele geçirerek yönetmek isterler. </u>Neticede, insanları gerçek hayattan koparıp, toplumla uyumunu bozarak hastalıklı bir ruh haliyle yaşamaları için çalışırlar. Ayrıca şeytanlarla işbirliği yapan büyücü, medyum vb.. gibi insanlarla dost olup, yaptıkları kötü işler nedeniyle yakalarını bırakmaz, onlar üzerindeki tasallutlarını  daha da artırırlar. Musallat oldukları insanların beynine yerleşip,  akıl bozukluğu, ileri safhada da delilik meydana getirirler. Cinlerde ve onlarla ilişkide olanlarda mantıksal bütünlük yoktur!.. Yaptıkları konuşmalarda, baştaki söylediklerine sonra ters düşerler!.. Çelişkili konuşurlar!.. Genelde çok asabidirler!.. İtiraz gördüklerinde şiddetle parlarlar!.. Çünkü bencildirler, kendilerini çok beğenirler, başkalarını küçümserler!.. Yalanları çoktur!.. Kendilerini daima büyük görüp, olabildiğince güçlü göstermeye çalışırlar!..
				</p><p align="justify">Tıp biliminin sebebini  açıklayamadığı psikolojik-ruhsal hastalıkların sebebi cin musallatıdır. Peygamberimiz: "Şeytan kanın damarlarda dolaştığı gibi, insanın damarlarında dolaşır" demiştir. Bu ifade düşmanımızın bedenimize girerek, haberimiz olmadan bizi ele geçirmeye yönelik faaliyette bulunması demektir. Musallatın etkisiyle, özellikle ruhsal ve buna bağlı olan beyinsel faaliyetler bozularak  duygu, düşünce, ve eylemlerimiz şeytanın tesiri altında kalır ve   yönlendirilir. Bu yönlendirme ile kişisel ve sosyal hayatımızı olumsuz yönde etkileyen davranış bozukluklarının ortaya çıkmasını istemektedirler. Böylece ele geçirdikleri insanı yaşadığı  gerçek  hayattan kopararak ruhen ve bedenen hastalanmasını istemekte, yada uyumsuz, hata yapan, kabahat hatta suç işleyen bir psikolojiye sahip olmasını sağlayarak, insanın helak olmasını amaçlamaktadırlar. 
				</p><p align="justify">Şeytanın insanı ele geçirmede ve yönetmekte kullandığı ilk eylem, insan beynine kendine ait olan ve insan ruhu ve metabolizmasına uygun olmayan şer (şeytani) bir enerji yüklemektir. Adeta bilgisayar virüsü gibi, insanın beyinsel faaliyetlerini aksatan hatta bozan, akıl melekelerini kullanmayı zayıflatan ve ileri safhada da durduran bir müdahale ile işe başlamaktadır. Bu müdahale ile zayıflayan insan ruhu, artık şeytanın baskısına hedef hale gelince, şeytan kendi metodlarıyla (Vehim-Korku-Kaygı-Vesvese-Kuşku) insana fikirlerini fısıldamakta ve bu fikirleri, zayıflayan insan iradesine kabul ettirmek için de duygusal baskıya tabi tutmaktadır. İç dünyasında yani ruhunda meydana gelen bu faaliyeti insan kendi duygu, düşünce ve fikirleri zanneder. Halbuki fıtraten insan iyi, doğru ve güzel olanı düşünüp gerçekleştirecek bir yaratılıştadır. Ama şeytan denilen görünmeyen bir düşmanın ruha müdahale etme ve kötülük öğretme yeteneğinden habersiz olan insan, bilmediği ve göremediği bu fıtri düşmanın tuzağına düşer.  Böylece insan ruhu-beyni şeytanın yönetimine girmekte ve insan, ruhsal ve psikolojik yönden hastalanmaktadır. Çünkü, insan kendi iradesiyle şeytanın iradesi arasında kalır. Davranışlarında çok belirgin zıtlıklar ve çelişkiler ortaya çıkar. Bu ikilem arasında kalan insan, doğru ile yanlışı ayırt etmekte zorlanmakta ve genellikle şeytani duygusal baskı ile şeytanın iradesini tercih ederek onun istediği şeyleri, yani yanlış olan eylemleri yapmaktadır. Uyumsuz dediğimiz kişilik bozukluğuna sahip olan ve yanlış davranışları düşünmeden gerçekleştiren tüm insanlar mutlaka musallata uğramıştır.
				</p><p align="justify">Şeytanın bu safhaya ulaşabilmesi için insanın ruhunu zayıflatması ve bunun için de insanı korkutması gerekir. Korkak bir ruh hali her zaman etkiye ve baskıya açıktır. Bunu bilen şeytanlar insanları korkutmak ve üzmek için uykuda korkutucu, rahatsız edici rüyalar gösterirler. Korkan ve panikleyen insanın ruhsal gücü zayıflar psikolojisi bozulur, kendine güveni azalır, akıl melekeleri sağlıklı çalışamaz ve içine kapanarak, şeytana karşı koyamaz hale gelir. Çünkü, artık o insanın içindedir. Amacı insanı dış dünyadan koparıp içe kapanmasını sağlamak ve sadece kendisi ile ilişkide olmasını istemektir. Böylece insan üzerindeki etkisini, gücünü artırarak onu daha kolay yönetmeyi ve hastalandırmayı amaçlamaktadır. 
				</p><p align="justify">Şeytan yukarıdaki aşamadan sonra hastalandırdığı insanda bazı belirtilerin ortaya çıkmasına sebep olur. Bu belirtilerin en ileri safhası ona görünmesi ve onunla beyninden iletişim kurarak konuşmasıdır. Bu musallatın en ağır olanıdır. Cin çarpmasına  yani musallatına uğrayan insan, beyni veya kulaklarıyla bir takım sesler, konuşmalar duyar, kulak çınlaması olur ve gerçek hayatla ilgisi olmayan bazı görüntüler, canlılar, varlıklar  görebilir. Yalnız kaldığında ise kendisini birinin takip ettiği hissini duyar ve korkuya kapılır. İç sıkıntısı, organik olmayan devamlı baş ağrısı, ruhsal yapı ve huylarda olumsuz değişiklikler ortaya çıkar. 
				</p><p align="justify">Cin musallatı büyü yolu ile olursa, insan eşyayı aslından farklı görebilir. Birbirini seven insanları çirkin gösterip, duygusal değişime yol açarak sevgiyi nefrete, tersi olursa nefreti sevgiye çevirebilir. Asabi davranmak, küfürlü, seviyesiz ve yersiz konuşmak, kendi kendine konuşup gülmek, takıntılı olup unutmamak veya çabuk unutmak, kutsallara karşı soğuk olmak, hatta nefret etmek, çabuk öfkelenmek, bağırmak, ağlamak, çelişkili, anlamsız ve hızlı duygu değişimi, içe kapanarak insanlardan uzaklaşmak, keskin ve sert bakışlar ve ani hareketler vb.. davranışlar cin musallatının belirtilerindendir. 
				</p><p align="justify">Bütün bu olaylar insanın iç aleminde meydana gelmektedir. Organik hastalıklar gibi somut bir sebebi olmadığından, hem hasta hem de çevresi bu olumsuz değişimi kolaylıkla anlayamaz. Hasta durumunu hem anlamada, hem de anlatmakta zorlanır. İnsanları ikna edemez ve sonunda içine kapanır, derdiyle başbaşa kalır. Bu içe kapanış musallatın artmasına neden olur, hastalığın derecesi giderek artar ve tedavisi zorlaşır.
				</p><p align="justify">Cin musallatına uğrayan insanlarda uykuda da bazı belirtiler ortaya çıkmaktadır;
					1.Uykusuzluk; yani insanın uykuya geç dalması ve sık sık uyanarak uykusuz kalması,
					2.Kabuslar ve korkunç rüyalar görerek korkmak, uykusundan bağırarak veya çığlık atarak uyanmak,
					3.Rüyada kedi, köpek, deve, yılan, aslan tilki ve fare gibi korkutucu ve tiksindirici hayvanları çokça görmek,
					4.Uyurken dişlerini gıcırdatmak, uyurken konuşmak, gülmek, ağlamak, inlemek, çığlık atmak,
					5.Uyurken yataktan kalkıp şuursuzca yürümek veya birşeyler yapmak,
					6.Rüyalarında yüksek bir yerden düştüğünü görmek, kendisini kabirde, dar ve sıkıntılı, ıssız yerlerde, bodrum, mağara, lağım, çöplük gibi korkunç, pis ve iğrenç yerlerde görmek,
					7.Rüyalarında korku veren kendisine eziyet eden, küfreden, aşağılayan, azarlayan vs aşırı uzun veya kısa tuhaf özellikleri olan insanlar veya varlıklar, mahluklar görmek. Gerçekte iyi geçindiği anne, baba, eş veya çocuklarını rüyalarında düşmanca tavırlar veya söylemler yaparken görmek, rüyalarında onlara karşı kin, öfke ve nefret duyguları algılamak. (Özellikle büyü ile cin musallatı olursa)
					8.Uyurken siyah karaltılar görmek, goril gibi kıllı korkunç görünüşlü mahlukların üzerine çöküp boğazını sıktığını hissetmek (Karabasan- Albastı), 
				</p><p align="justify">Özet olarak; korkutucu, sıkıntılı ve yorucu bütün rüyalarda şeytanların insana olan tesiri ve baskısı vardır. Onun kişilik özelliklerini bozmak için rüyalarda bu amaç doğrultusunda kurguladıkları senaryolar ile onların ruhlarını tesir altdında bırakarak duygusal yönden etki altına alıp bu eğilimin gerçek hayattada devamını ve insanın davranışlarını amaçları doğrultusunda değiştirmelerini baskılarlar. Bu tür rüyaları sık görenler musallata uğramışlardır. Tedavi edilmeleri ve davranışlarındaki içgüdü kaynaklı nefsi, şehevi istek ve duyguları terketmeleri gerekir. Çünkü şeytanlar böyle düşünen, inanan ve yaşayan insanlarla daha fazla uğraşırlar. Çocuklar ile uğraşmalarının nedeni ise, onların yanlış davranışlar edinerek büyümeleri ve karakterlerinin bozulmalarını istemeleridir. Böyle büyüyen bir insanı adeta kendi eğitiminden geçirerek ileride şer bir insan olarak amacına hizmet etmesini istemektedir.
				</p><p align="justify">İnsanların cinlerden korkmasına gerek yoktur. Çünkü cinler yaratılış olarak insandan daha zayıf canlılardır. İnsanlara somut olarak zarar veremezler. İnsanları boğamazlar ve öldüremezler. Sadece gerek rüya aleminde, gerekse musallatın ileri safhasında gerçek alemde, insanları korkutup iradelerini etkileri altına almaya çalışırlar. Onlara yanlış fiiller yaptırıp başlarını belaya sokmak, diğer insanlarla ilişkilerini, işlerini, ticaretlerini bozmak vb. olumsuz bir duruma sokarak kendilerini ve çevrelerini üzmek, sıkıntıya ve zarara uğratarak hayatlarını çekilmez hale getirmek isterler.
				</p><p align="justify">Cinler özellikle Allah'tan korkan ve ona inanan iman ve ibadet eden mümin insanlardan çekinirler, onlara Allah'ın izni ile zarar veremezler. Çünkü onların ruhları manen cinden daha güçlüdür. Allah insanı yarattıklarının bir çoğundan üstün kılmıştır. Yaratılış özellikleri bakımından insan cinden daha üstündür. Allah her insanı koruyan melekler görevlendirmiş ve görevli melekler insanı gece-gündüz takip ederek, cinlerin ve insanın göremediği herşeyin kötülüğünden ve zararından eceli gelinceye kadar korumaktadır. Bunu bilen ve iman eden insanın Allah'tan başka bir varlıktan korkmasına gerek yoktur. Ama yine de cinlerin musallatına uğrayan insanın, bu konu ile ilgili doğru bilgisinin olmayışı, yada yanlış ve hurafe bilgilere inanması nedeniyle korktuğu ve musallatın ilerlemesi ile yukarıda bahsedilen belirtileri gösterip ve rahatsızlıklara yakalandığı da aşikârdır.
				</p><p align="justify">Peki bu sıkıntının bir çözümü var mıdır? Musallata uğrayan insanın öncelikle durumunun farkına varmalı ve sıkıntılarının sebebini bulmalıdır. Bu sitede hakikate uygun olarak yazılmış sahih bütün bilgileri dikkatle okuyup, bu bilgiler ile teşebbüse geçmesi gerekir. Hastalığın organik sebeplerle olma ihtimaline yönelik, şifayı öncelikle tıb biliminde arayıp, çaresiz kaldığında ise bu konularda bilgili, inançlı ve tecrübeli insanlara müracat etmesi doğru olur. İçindeki düşmana kendini kaptırmadan onunla mücadele etmesi ve kendi iradesiyle hareket etmesi önemlidir. Eğer başarılı olamıyorsa yardım almalıdır. Özellikle sitemizin ruhumuzu tanıyalım sayfasını dikkatle okuyup, öğrenmelidir.
				</p><p align="justify">Bu sıkıntının çözümü; Eğer ne şekilde olursa olsun bir insan musallata uğradığına inanıyorsa ve tıbbi tedaviden fayda görememişse ve kendi iradi mücadelesi ile bu sıkıntıyı aşamıyorsa mutlaka ikinci ehil bir kişiden yardım almalıdır. Bedeni ve ruhuna nüfuz etmiş şeytani enerjinin ondan uzaklaştırılması gerekir. Bu da, Allah'ın yardımı ile şerefli, hayırlı ulvi ruhların bu habis ruhlara karşılık vermesi ile olur. Onlar habis ruhların menfi tesirlerini Allah'ın yardımıyla hasta insandan uzaklaştırıp defederler. Onların fiillerine karşı çıkıp, iptal edilmesine yardımcı olurlar. İşte bu iyilerin vesilesiyle olur. Sitemizin cin-büyü musallatının tedavisi nasıl yapılır? bölümünde bu konu ile ilgili açıklamalar yapılmıştır.</p>
			</div>
		</div>
	</div>
	<!-- End FA Questions Text -->