<!-- FA Questions Text -->
<div id="js__scroll-to-section" class="g-container--md g-padding-y-80--xs g-padding-y-125--sm">
	<h2 id="textHead" class="g-font-size-32--xs g-font-size-36--md g-text-center--xs g-margin-b-80--xs">METAFİZİK ALEM İLE İLETİŞİM; DUA ETMEK...</h2>
	<div class="g-text-left--xs">
		<div>			
			<p><u>De ki: "Sizin duanız olmasaydı Rabbim size değer verir miydi? (Furkan-77)</u></p>
			<p>DUA NEDİR: Birisini çağırmak, birisini bir şeye sevk etmek. İslami manada dua; Allah'a (cc) karşı rağbet, niyaz, yalvarış, tazarru, salat, namazdır. Cenab-ı Hakk'tan hayır ve rahmet dilemek, Allah'ın rızasını, hidayet ve istikamete muvaffakiyeti dilemek, yalvarmak, peygamber (a.s) a salavat getirmektir. (Osmanlıca - Türkçe yeni lügat)</p>
			<p>Hemen bütün ilahi din ve diğer inanç sistemlerinde iman ve itaatin bir rüknüde dua etmektir. Dua imana sahip olmanın bir belirtisidir. Çünkü; insan Dünya'da yaşadığı  hayat şartları nedeniyle ihtiyacı çok olan zayıf bir canlıdır.  Maddi ve manevi pek çok şeye ihtiyaç duyar. İhtiyaçlarından maddi olanlarını gücünün yettiğince çalışarak elde etmek isterse de, çoğu zaman çalışmasının karşılığını alamaz ve çaresiz kalır. Tabiatının gereği heva, heves ve hayallerinin peşinden koşarak ömrünü geçirebilir. İhtiyaç ve isteklerini akıl, mantık ve bilimsel hakikatler doğrultusunda elde etme yolunu izlediği gibi, isteklerini yanlış inanç, fikir ve yöntemler ile de elde etmeye çalışabilir. Bütün bu süreç boyunca bedeni harekete geçirip kullanan, ruhu yorulur, açmaza düşer ve tıkanır. Bu noktaya gelen insan bedenen ve ruhen çaresiz kalır. Maruz kaldığı bela, musibet, sıkıntı, hastalıkları gidermek ve diğer somut ihtiyaçlarını karşılayabilmek için, çevresinden beklediği yardımı alamaz veya ihtiyacı onların imkanlarının üzerinde ise  insan, ruhunun yapısal özelliği gereğince üstün bir metafizik varlıktan yardım istemeye yönelir.</p> 
			<p>İnsan, eğer hak bir inanca sahipse bu doğrultuda her varlığın yaratıcısı olan, her işi yapmaya ve yaratmaya kadir olan yüce Allah'tan yardım ister. Fakat insan batıl bir inanca sahipse veya hurafeler ile hareket ediyorsa, doğrudan Allah'tan istemeyip geçmiş dönemlerde yaşandığı gibi elleriyle yaptıkları putlardan ve diğer metafizik varlıklar olan melekler ve cinlerden ister. Bu noktada, birbirinden inanç yönüyle farklı olan her iki insan, metafizik varlıklar ile bu alemde doğrudan muhatap olamayacaklarını bildiklerinden, bu varlıkların kendisini görüp işittiğine inanarak, onlara niyet ve söylemleri ile yönelir, müracat eder, isteklerini bildirir ve  yalvarır. </p>
			<p>İşte insanın inancı ve ihtiyacı gereğince gerçekleştirdiği bu fiile dua denir. İnsanlar üstesinden gelemedikleri hastalık, bela ve sıkıntıları aşabilmek ve maddi ve manevi diğer isteklerine ulaşabilmek için gaybi alemden dua vesilesiyle yardım isterler. Dua etmek insanın ruhsal yapısının bir tezahürüdür.</p>
			<p>İslam dini ve kutsal kitabı Kur'an-ı Kerim, bizlere hak olan tevhid inanç sistemini öğreten yegane kaynaktır. Cenab-ı Allah hem Kur'an-ı Kerim'de hem de Resulullah'ın sünnetinde islam dininin diğer ibadetlerinde olduğu gibi, dua konusunda da bize hak olan doğru niyet ve yöntemi bildirmiştir. Bundan farklı olan dua yöntemleri batıl olup, Allah muhafaza insanı günahkar yapar, küfre sokar. Batıl yöntemlerle Cenab-ı Allah dışında veya Allah ile birlikte başka varlıklara ısrarla dua etmek, istemek, yalvarmak insanı asi yapar ve şeytanların bize musallat olmasına sebep olur.</p>
			<p>Cenab-ı Allah Kur'an-ı Kerim'de, dua konusunda aşağıda belirtilen ayetler ile inanan kullarına hakikati bildirmektedir. Bir müslümanın bu doğrultuda hareket etmesi inancının gereğidir;</p>
			<ul><li>1- Şayet kullarım, sana benden sordularsa gerçekten ben çok yakınımdır. Bana dua edince duacının duasını kabul ederim. O halde benim davetime (islama) koşsunlar ve bana hakkıyla iman etsinler ki, doğru yola gidebilsinler. (Bakara-186)</li>
				<li>2- De ki: "Sizin duanız olmasaydı Rabbim size değer verir miydi? (Furkan-77)</li>
				<li>3- En güzel isimler Allah'ındır. Bundan dolayı Allah'a onlar ile dua edin ve onun isimlerinde sapıklık eden inkarcıları terk edin. Onlar (inkar edenler) yakında yaptıklarının cezasını çekeceklerdir. (Araf-180)</li>
				<li>4- Allah'tan başka sana faydasıda zararıda dokunmayacak olan şeylere yalvarma. Eğer yalvarırsan o zaman hiç şüphesiz sen zalimlerden olursun. (Yunus-106)</li>
				<li>5- Allah ile birlikte başka bir tanrıya tapıp yalvarma! O'ndan başka ilah yoktur. O'nun zatından başka herşey helak olacaktır. Hüküm onundur siz ona döndürüleceksiniz. (Kasas-88)</li></ul>
				<p><u>Bu ayetlerden şu sonuçları çıkarabiliriz:</u></p>
				<p>Cenab-ı Allah yarattığı kullarının kendisine dua etmesini ister, dualarını işitir, kabul eder. Kendisine dua eden kullarına değer vereceğini bildirir. Ama bu duaların kabul edilmesi için kullarının şirke, zulme bulaşmadan emrettiği şekilde zatına hakkıyla iman etmesini ister.</p>
				<p>Kendisine, fiillerinin kaynağı olan isim ve sıfatlarıyla dua edilmesini ister. Yani rızık isteyen bir kul Cenab-ı Allah'a Rezzak (rızık veren) ismiyle dua etmelidir. Bu nedenle kamil bir müslümanın Allah'ın isim ve sıfatlarını bilmesi gerekir. Böyle müslümanlar cennetle müjdelenmiştir.</p>
				<p>Cenab-ı Allah, isim ve sıfatlarını sapık, batıl fiil ve yöntemlere alet edenleri şiddetle uyarıyor. Terk edilmesini istiyor.</p> 
				<p>Özellikle tesirli dua kamuflajı, kandırmacasıyla Allah'ın isimleri ve ayetlerini kullanarak Vefk ilmiyle uğraşanların bu uyarıyı dikkate almalarını ve yaptıkları şirk işini terk etmelerini tavsiye ederim. Allah'ın isimlerini ve Kur'an ayetlerini kullanarak islamda yeri ve izahı mümkün olmayan vefk yapımının bir büyü yöntemi olduğu aşikardır. </p>
				<p>Çünkü; vefk yapımında kullanılan yöntemle o isim, sıfat veya ayetin hadimleri adı altında şeytanların isimleri  belirlenir. Vefk yapımından sonra hazırlanan duada; Allah, melek ve bu şeytanların isimleri birlikte zikredilir. Alenen Allah'a şirk (ortak) koşan bir mahiyette hazırlanan dua ile isteklere ulaşılması amaçlanmaktadır. </p>
				<p>Vefk yaptırmak ve bu vefkin duasıyla Allah'a yalvarmak, şirk koşarak küfre girmektir. Zaten vefk yaparak para kazananların durumunun vehametini açıklamaya izah yoktur.</p> 
				<p><u>Vefk yapanlara ve yaptıranlara şu soruyu sormak lazım; Peygamberimizin sünnetinde vefk var mıdır? Peygamberimiz ve diğer peygamberler vefk yaparak mı? Allah' a dua etmişlerdir. Kur'an- ı Kerim'de ve sünnette vefk ile ilgili bir ayet ve hadis var mıdır? Kur'an-ı Kerim'de dualar tesirli veya tesirsiz diye ayrılmış  mıdır?</u></p>
				<p><u>Cenab-ı Allah'ın işlerini yapmada ve yönetmede hadimlere ihtiyaçmı duyar? Haşa; Allah acizmi ki yardımcılara ihtiyaç duyuyor? Tevhid inancında Allah kendisine ortak kabul ediyormu ki, duada melek ve şeytanların isimlerini Allah'ın ismiyle birlikte zikrediyor ve onlardan da istiyorsunuz. Bu nasıl bir tevhid inancı? gibi yüzlerce soru sorulabilir. </u></p>
				<p></u>Bu sorulara altta yazılı olan ayetleri okuduğunuzda, cevabını kolayca bulursunuz;</u></p>
				<p>Kehf 50: Yine o vakti hatırla ki biz, meleklere: "Adem'e secde edin!" demiştik. İblis hariç olmak üzere onlar hemen secde ettiler. İblis cinlerdendi, Rabbinin emrinden çıktı. Şimdi siz beni bırakıp da İblis'i ve soyunu dostlar mı ediniyorsunuz? Halbuki onlar sizin düşmanınızdır. Zalimler için bu ne kötü bir değişmedir</p>
				<p>Kehf 51: Ben, onları (İblis ve soyunu) ne göklerin ne yerin yaratılışında, ne de kendilerinin yaratılışında şahit tutmadım ve<u> hiçbir zaman doğru yoldan çıkanları yardımcı edinmiş değilim. </u></p>
				<p>Büyücülüğün arka planında olağanüstü bir takım olayları cinler vasıtasıyla gerçekleştirileceği inancı hakimdir. Bu yüzden de bu işle uğraşan bazı yahudi insi şeytanları (büyücüleri) bu iddialarını Hz Süleyman'ın cinlere hakim olması ile desteklemişlerdir. Hz Süleyman'ın, cinleri yönetmesini ve diğer birtakım doğaüstü işleri büyücülükle sağladığı iddiasını ileri sürmüşlerdir.</p> 
				<p>Fakat bu iddiaya Cenab-ı Allah Kur'an da cevab vermiştir. Hz. Süleymanın fiziki ve manevi kuvvet ve kudreti sadece ona has olan ve başka hiçbir kuluna Cenab-ı Allah'ın  vermediği bir ilimle gerçekleşmiştir. Bakara 102 de Hz Süleymanın değil, ona büyücü diyen insi şeytanlar, büyücülük meslekleri nedeniyle lanetlenmişlerdir. Zamanımızın büyücüleri de hala bu zihniyetin izleyicileridir. Dikkat edilmesi gerekir.</p>
				<p>Hak ve hakikate uygun dua şekli şöyledir: Hadislerde beyan edildiğine göre, peygamberimiz koltuk altı beyazlığı görünecek kadar ellerini semaya kaldırarak, doğrudan kalbi ve diliyle Allah'a dua etmiş ve istemiştir. Diğer peygamberlerin de dua şekli böyledir. Kalbden gizlice veya dilleriyle açıkça dua etmişlerdir. Bunun dışındaki tüm dua yöntemleri İslam dışıdır, batıldır.</p>
				<p>Burada bir konuyu daha belirtmek isterim ki; Bazı medyumlar meleklere dua edip onlardan istemeyi sakıncalı görmemektedirler. Meleklerin Allah'ın muti (itaatkar) kulları olması ve Allah'ın emriyle hareket etmelerinden dolayı bu tür dua şeklini masum göstermektedirler. Bu tür dua şekli de batıldır. Çünkü; Kur'an-ı Kerim'de melekler hakkında aşağıdaki ayetlerde, onların Allah'ın emri dışında hareket etmedikleri ve hiçbir yetkilerinin olmadığı açıkça ifade edilmiştir. Allah ile birlikte başka bir varlığın ismini zikrederek veya Allahı dışlayarak onun dışındaki diğer varlıkların isimlerini zikrederek (melek-cin) dua etmek, istemek veya yalvarmak islama göre küfre girmektir. </p>
				<p>O zaman, Allah'ın emri dışına çıkmayan melekler kendilerine yapılan dualara karşılık veremiyorlarsa, neden doğrudan Cenab-ı Allah'a değil de, meleklere dua edilip onlardan isteniyor? diye sorulduğunda; Cevabı, şeytanın insanı sağ taraftan (inancın zayıf olmasından faydalanarak vefk mantığında olduğu gibi islami bir görüntü ile) aldatıp şirke düşürme fiilidir. Aşağıdaki ayetlerde bu duruma işaret edilmektedir:</p>
				<ul><li>1- Senden önce hiçbir peygamber göndermedik ki, ona şöyle vahyetmiş olmayalım; Gerçek şu ki, benden başka ilah yoktur. Onun için bana ibadet edin. (Enbiya-25)</li>
					<li>2- Böyle iken dediler ki (kafirler): Rahman çocuk edindi. Allah bundan münezzehtir. Doğrusu melekler Allah'ın çocukları değil, ikram olunmuş kullarıdır. (Enbiya-26)</li>
					<li>3- Onlar (melekler) Allah'ın sözünün önüne geçmezler, hep onun emriyle hareket ederler. (Enbiya-27)</li>
					<li>4- Allah, onların (meleklerin) yaptıkları ve yapacaklarını bilir. Onlar, Allah'ın hoşnut olduğu kimseden başkasına şefaat etmezler. Hepsi de onun korkusundan titrerler. (Enbiya-28)</li>
					<li>5- İçlerinden kim: Ben, O'ndan (Allahdan) başka ilahım derse, biz ona cehennemi ceza olarak veririz. Zalimleri biz böyle cezalandırırız. (Enbiya-29)</li>
					<p>Sitemizin diğer bölümlerinde açıklandığı gibi, metafizik varlık olan cinler (şeytan) den istemek, bunun için büyü yapmak ve yaptırmak ise bütün ilahi dinlerde lanetlenmiştir. Yapan, yaptıranda tövbe edip vazgeçmediği sürece cehennemliktir denilmiştir. Zaten şeytanların yalan vaad ve aldatmadan başka bir fiilleri yoktur. Hakiki tesir eden yani hayrı ve şerri yaratan Allah'tır. </p>
					<p>Şeytanlarda, meleklerde Cenab-ı Allah'ın iradesi ve kudreti altındadır. O'nun istemediğini hiçbir varlık yapamaz, istediğini ise engelleyemez. O nedenle  kamil müslümanların sadece Allah'a dua edip ondan istemesi yegane hakikattır. Başka alternatifler hem günah, hem de Allah rıza göstermedikçe nafile, boşuna çabalardır. Cenab-ı Allah hayra rıza gösterir, şerri yaratsa da rıza göstermez, şerri işleyeni sorumlu tutar ve cezalandırır.</p>
					<p><u>O zaman hakka uygun islami dua şekli nedir? diye sorulduğunda; Bütün peygamberlerin yaptığı gibi Allah'dan başka hiçbir varlık düşünmeden, onlara niyet etmeden, ismini zikretmeden namazlardan sonra veya herhangi bir zamanda doğrudan Rabb'imizden istemeliyiz ve ona dua etmeliyiz.</u></p>
					<p>Duada bir ibadet şeklidir. İhtiyacın belirmesi dua ibadetinin yapılmasının zamanıdır. Yapılan dualarda istek ve dileklerimiz hemen gerçekleşmediğinde duam kabul olmadı diye, vazgeçmemeliyiz. Biz istemeliyiz, ama duaya cevabın ne zaman verileceğine karışmamalıyız, sabırla beklemeliyiz. Cenab-ı Allah durumumuzu bizden daha iyi bildiğinden, neticeyi kamil bir imanla ona havale etmeliyiz. Ayrıca dualarımızın kabul olması için ibadetlerimize, dinimizin emir ve yasaklarına titizlikle riayet etmeli ve özelliklede haram rızık yememeliyiz.</p>
					<p>Cenab-ı Allah Kur'an-ı Kerim'de peygamberlerin dualarından örnekler indirmiştir. Dünyevi ve uhrevi isteklerimizi Kur'andaki dua örnekleriyle yapabiliriz. Ayrıca peygamberimizin hadislerinde belirtilen ifadeler ile de dua edebiliriz. Kalbimizde ve zihnimizde beliren kendimize ait kelimeler ile de dua edebiliriz. </p>
					<p>Dua, kul ile Rabbi arasındaki karşılıklı bir özel bir bağdır, iletişimdir. Kul ister, Rabbi verir. Allah duaya icabet etmeseydi, dua etmemizi istermiydi? Dualarımızla Rabbimize iltica etmekte, ona sığınmakta ve ondan yardım dilemekteyiz. İyyake na'büdü ve iyyake nestain! yalnız sana ibadet eder ve yalnız senden yardım dileriz mantığıyla sadece ona yönelirsek, O'da bize icabet edeceğini vaad ediyor.</p>
					<p>Toplumumuzda yaygın olan yanlış dua ritüellerinden de uzak durmalıyız. Bir ağaca bez bağlayıp dilek tutmak, bir türbeye gidip yatırdan yardım istemek, dua kabul olsun diye belli yerlere para atmak, taş yapıştırmak, dar deliklerden geçmek vb uygulamaların dinimizde yeri yoktur. Bunlar hurafe olup batıl uygulamalardır. İnanarak yapanı günaha sokar.</p>
					<p>Aşağıda Kur'andan çıkarılan dua örnekleri bulunmaktadır. Bunları ezberleyerek ihtiyacımıza uygun duaları yeri ve zamanı geldiğinde yapabiliriz.</p>
					<ul>
						<li>
						Rabbena atina fid dünya haseneten ve fil ahireti haseneten ve gına azaben nar. (Bakara 201-Ey Rabbimiz; Bize dünyada ve ahirette bir güzellik ver ve bizi ateş azabından koru) Bu dua dünya ve ahiret hayrı için yapılmalıdır.</li>
						<li>Rabbena innena amenna fağfirlena zünubena ve gına azaben nar.                                         (Al-i İmran 16-Ey Rabbimiz ; Biz inandık iman getirdik, artık bizim suçlarımızı bağışla ve bizi ateş azabından koru) Bu dua tevbe edip, afv dilemek ve cehennemden muhafaza için yapılmalıdır.</li>
						<li>Rabbi inni euzubike ve zürriyyetehe mineşşeytanirracim                                                          (Al-i İmran 36-Rabbim onu ve soyunu  kovulmuş şeytandan sana ısmarlıyorum) Bu dua şeytandan muhafaza için yapılmalıdır.</li>
						<li>Rabbi hebli min ledünke zürriyyeten tayyibah inneke semi ud dua                                          (Al-i İmran 38-Rabbim bana katından hayırlı bir nesil ver, şüphesiz sen duayı hakkıyla işitensin) Bu dua hayırlı evlat için yapılmalıdır.</li>
						<li>Rabbi vec'al lena min ledünke veliyyen, vec'al lena min ledünke nasira                               (Nisa 75-Rabbim bize katından iyi idare edecek bir sahip ve bize katından bir kurtarıcı gönder) Bu dua bela, musibet ve sıkıntıdan kurtulmak için yapılır.</li>
						<li>Ya Rezzak-ı Kerim-i ya Allah, verzukna, ve ente hayr ur razigin                                           (Maide 114-Ey rızık verici cömert Allah'ım rızık ver sen rızık verenlerin en hayırlısısın) Bu dua iş ve rızık için yapılmalıdır.</li>
						<li>Hasbunallahü seyu'tinallahü min fedlihi ve rasulühü inna ilallahi rağibün                         (Tevbe 79-Bize Allah yeter. Allah bize lütuf ve ihsanlarından yine verir. Bizim bütün rağbetimiz Allah'adır) Bu dua Allaha tevekkül etmek ve ondan nimet istemek için yapılır.</li>
						<li>Bismillahi mecraha ve mürseha inne rabbi le gafür ur rahim.                                                 (Hud 41-Allah'ın adıyla binin içine, onun akışıda duruşuda Allah'ın adıyladır. Hiç şüphesiz Rabbim gerçekten çok bağışlayıcı, çok esirgeyicidir.) Bu dua kara, deniz veya hava yolculuğu yaparken yapılmalıdır.</li>
						<li>Ya Hafiz ül Kadir-i Ya Allah ihfazna, Allahü hayrün hafizen ve hüve erhamür rahimin.      (Yusuf 64-Ey korumaya Kudreti olan Allahım, koru-muhafaza eyle, En hayırlı koruyucu Allahtır. Ve o merhamet edenlerin en merhametlisidir.) Bu dua maddi ve manevi şer, bela ve musibetlere karşı yapılmalıdır.</li>
						<li>Rabbehü rabbi la tezerni ferden ve ente hayr ül varisin.                                                      (Enbiya 99-Rabbim beni tek başıma bırakma sen varislerin en hayırlısısın) Bu dua evlat, hayırlı yoldaş istemek için yapılır.</li>
						<li>Ya Şafi-i Selam ü Ya Allah veşfi ve iza maridztü fe hüve yeşfin.                                             (Şuara 80-Ey selamete ulaştıran şifa veren Allahım, şifa ver, hastalandığım zaman bana o şifa verir) Bu dua hastalıktan kurtulmak, şifaya ulaşmak için yapılır.</li>
						<li>Rabbi hebli hükmen ve elhikni bissalihin.                                                                                  (Şuara 83-Ya Rab bana hikmet ver ve beni iyiler zümresine kat) Bu dua hidayet, ilim ve hikmet sahibi iyi bir mümin olmak için yapılır.</li>
						<li>Rabbi inni zalemtü nefsi fağfirli                                                                                                 (Kasas 16-Rabbim kendimi ziyana uğrattım beni bağışla) Bu dua günaha girdikten sonra afv dilemek için yapılır.</li>
						<li>Rabbi inni lima enzelte ileyye min hayrin fakir                                                                         (Kasas 24-Rabbim doğrusu bana indireceğin her hayra  muhtacım) Bu dua her türlü ihtiyaç için yapılır.</li>
						<li>Rabbin surni alel kavmil müfsidin                                                                                        (Ankebut-Rabbim şu fesatçılar güruhuna karşı bana yardım eyle) Bu dua zalimler, düşmanlar ve kafirlere karşı yardım istemek için yapılır.</li>
						<li>Rabbi hebli mines salihin                                                                                                            (Saffat 100-Rabbim bana salihlerden bir oğul ihsan et) Bu dua imanlı salih evlat istemek için yapılmalıdır.</li>
						<li>Allahu  latifun bi ibadihi yerzuku men yeşeu ve hüve kaviyy ül Aziz                                            (Şuara 19-Allah kullarına çok lütufkârdır. Dilediğine rızık verir. O çok kuvvetlidir, çok güçlüdür) Bu dua rızık, iş, meslek istemek için yapılır.</li>
						<li>Allahü ennehü eğna ve ekna                                                                                                    (Kamer 48-Şüphesiz Allah zengin eden ve sermaye verendir) Bu dua ticaretin gelişmesi, işlerin yolunda gitmesi için yapılmalıdır.</li></ul>
						<p>Cenab-ı Allah Ganiy ül Kerim olup aynı zamanda Rahman ve Rahimdir. Sonsuz zenginlik sahibi, ihsan edici, cömert, kerem sahibi, koruyan esirgeyen, kullarını seven, acıyan ve afv edendir. Bütün ihtiyaçları ancak o karşılar. O'ndan başka tüm varlıklar ona muhtaçtır ve sadece O'ndan istemelidir. Doğru olan budur. Rabbim  dünya ve ahiret yönelik bütün dualarımızı kabul etsin. Amin</p>

					</div>
				</div>
			</div>
			<!-- End FA Questions Text -->