<div id="js__scroll-to-section" class="g-container--md g-padding-y-80--xs g-padding-y-125--sm">
	<h2 id="textHead" class="g-font-size-32--xs g-font-size-36--md g-text-center--xs g-margin-b-80--xs">
		BÜYÜ VE CİN MUSALLATINDAN KORUNMAK VE KURTULMAK İÇİN BİLİNMESİ VE YAPILMASI GEREKENLER
	</h2>

	<div class="g-text-left--xs">
		<div>
			
			<p>1- CENAB-I ALLAH KUR'AN-I KERİM'DE KULLARINA ŞÖYLE EMRETMİŞTİR:</p>
			<p>ARAF SURESİ 3: (Ey insanlar) Rabbinizden, size indirilene (Kur'an-ı Kerim) uyun ve O'ndan başka dostlara uymayın. Ne kadar da az öğüt alıyorsunuz!</p>
			<p>İSRA SURESİ 82: Biz Kur'an'dan, iman edenler için bir şifa ve rahmet kaynağı olan ayetler indiriyoruz. Zalimlerin de ancak zararını artırır.</p>
			<p>NAHL SURESİ 98: Şimdi Kur'an okumak istediğin zaman önce o kovulmuş şeytandan Allah'a sığın. 99: Şüphesiz ki, iman edip te Rablerine tevekkül edenler üzerinde o şeytanın hiçbir nüfuzu yoktur. 102: Onlara de ki: "Kur'an'ı Cebrail, iman edenlere sebat vermek, müslümanlara bir hidayet ve bir müjde olmak için Rabbinin katından hak olarak indirdi"</p>
			<p>ZUHRUF SURESİ 36: Her kim Rahman olan Allah'ın zikrinden yüz çevirirse biz ona bir şeytan musallat ederiz. Artık o şeytan onun yakın dostudur. 37: Şüphesiz ki bu şeytanlar onları yoldan çıkarırlar. Onlar da kendilerinin doğru yolda olduklarını sanırlar. 62: Sakın şeytan sizi doğru yoldan alıkoymasın. Gerçekten o sizin için apaçık bir düşmandır.</p>
			<p>HACC SURESİ 4: O şeytan ki, hakkında şöyle hüküm verilmiştir: Şüphesiz kim onu dost edinirse, o muhakkak onu  saptırır ve doğruca cehennem azabına götürür.</p>
			<p>FATIR SURESİ 6: Çünkü şeytan size düşmandır. Siz de onu düşman tutun. O etrafına toplanan taraftarlarını ancak cehennemliklerden olsunlar diye davet eder.</p>
			<p>ŞUARA SURESİ 221: Şeytanların kime ineceğini size haber vereyim mi? 222: Onlar, günaha ve iftiraya düşkün olan herkesin üzerine inerler. 223: Onlar, şeytanlara kulak verirler, onların çoğu yalancıdır.</p>
			<p>NİSA SURESİ 118: Allah o şeytana lanet etti. Ve o da: "Elbette senin kullarından belirli bir pay alacağım, onları mutlaka saptıracağım, onları boş kuruntularla oyalayacağım." 120: Şeytan onlara vaad eder ve onları boş umutlar ile oyalar. Oysa şeytanın onlara vaadi, aldatmadan başka birşey değildir.</p>
			<p>HİCR SURESİ 39: İblis şöyle dedi: "Rabbim! Beni saptırdığın için, mutlaka ben de yeryüzünde onlara günahları süsleyeceğim ve onların hepsini mutlaka azdıracağım!" 40: "Ancak içlerinden ihlaslı kulların müstesnadır" 41: Allah şöyle buyurdu: "İşte bana ulaşan dosdoğru yol budur" 42: "Sana uyan azgınlardan başka, kullarımın üzerinde hiçbir nüfuzun yoktur" 43: "Şüphesiz ki, onların hepsine vaat edilen yer cehennemdir"</p>
			<p>Şeytanın (iBLİS) misyonu insanlara musallat olarak onları hak yoldan uzaklaştırmak, inançsız ve günahkar bir hayat yaşatarak dünya ve ahiret saadetini kaybettirmektir. Bu görevini gerçekleştirmek için yapısal özelliklerinin avantajı ile özellikle insan ruhuna tesir edip onu ele geçirmeye ve amacına uygun yönetmeye çalışmaktadır. Bütün insanlar onun hedefinde olup çeşitli şekillerde musallata maruz kalmaktadırlar. Musallat yöntemleri genel manada iki başlık altında gerçekleşir. 1- Vesvese (şüphe, kuşku) vererek insan iradesini zayıflatıp yanıltarak, insan ruhuna baskıladığı telkinler ile hatalı karar aldırmak ve davranışlar yaptırmaktır. 2- Ayrıca ruhsal ve organik güdü ve dürtülerimizi ( yeme-içme, kin, nefret, korku, kaygı, öfke, saldırganlık, cinsellik vb) azdırmak suretiyle, yine aşırı davranışlara yöneltmek için biyolojik ve duygusal istek arzu ve tutkularımızı fitlemekte yani kışkırtmaktadır. İşte bu saldırılara karşı koyabilmenin yol ve yöntemini Allah aşağıdaki ayetlerde bize bildirmiştir.</p>
			<p>ARAF 200: Eğer şeytandan bir vesvese, bir kışkırtma gelirse hemen Allah'a sığın. Muhakkak ki, Allah hakkıyla işiten, ve kemaliyle bilendir.</p>
			<p>FUSSİLET 36: Eğer şeytandan gelecek kötü bir düşünce seni dürtecek olursa hemen Allah'a sığın. Çünkü o herşeyi işitir ve bilir.</p>
			<p>MÜMİNUN SURESİ 97: De ki: Rabbim! şeytanların kışkırtmalarından sana sığınırım! 98: Onların yanımda bulunmalarında da sana sığınırım.</p>
			<p>FELAK SURESİ 1: De ki: Sabahın Rabbine sığınırım, 2: Yarattığı şeylerin şerrinden,  3: Karanlık çöktüğü zaman gecenin şerrinden, 4: Düğümlere üfleyen büyücülerin şerrinden, 5: Ve haset ettiği zaman hasetçinin şerrinden.</p>
			<p>NAS SURESİ 1: De ki: Ben insanların Rabbine sığınırım, 2: İnsanların sahibine,         3: İnsanların gerçek İlahına, 4: O sinsi vesvesecinin şerrinden, 5: O ki; insanların göğüslerine vesveseler fısıldar, 6: Gerek cinlerden, gerek insanlardan,</p>
			<p><u>BİZİ ŞEYTANDAN  ANCAK ALLAH KORUR.  KUR'AN-I KERİM'DE BİLDİRDİĞİ ŞEKİLDE ONA SIĞINMAYAN İNSAN, ŞEYTANLARIN MUSALLATINDAN ASLA KORUNAMAZ. KORUMANIN GERÇEK MANADA OLMASI İÇİN RABB'İMİZİN BİZE KUR'AN-I KERİM VE HZ. MUHAMMED İLE BİLDİRDİĞİ İSLAM DİNİNİN İMAN, İBADET, EMİR VE YASAKLARINI ÖĞRENEREK HAYATIMIZA REHBER YAPMALIYIZ. AŞAĞIDA BU DOĞRULTUDA ÖZET BİLGİ VERİLMİŞTİR:</u></p>
			<p>1- Allaha, sadece dua edilerek sığınılamaz. Bu hakikat, ancak Allah’ın Kur'an-ı Kerim'de bildirdiği emir ve yasakları öğrenip, hayatımızı bu doğrultuda yaşarsak gerçekleşir.</p>
			<p>2- Öncelikle nefsimizi azdıran ve günah adı verilen bir kısmı da hukuken suç olan aşırı, azgın fiilleri işlemekten uzak durmalıyız. Çünkü günah ile aşırı giden nefis, şeytanı kendine cezbeder ve ona arkadaş olur. Şeytan yaptığımız yanlış ve kötü fiilleri nefsimize doğru ve güzel gösterir. Onları asla terketmemizi istemez. sonunda bizi asi ve günahkar bir insan yaparak dünyada mutsuzluğa, ahirette de cehenneme sürükler.</p>
			<p>3-Bizi Allah'a karşı asi yapan ve fert, aile ve toplum hayatını alt üst eden büyük günahlardan uzak durmalı, eğer hata veya cahillikle işlersek, hemen tevbe ederek ve bir daha yapmamız gereken günahlar:</p>
			<p>4- Allah'a melekler, cinler veya diğer varlıklar ile asla şirk-ortak koşmamalıyız. Sadece O’na ibadet etmeli ve sadece ondan istemeliyiz. </p>
			<p>5- İnsan öldürmemeli, hiçbir varlığa somut ve soyut işkence yapmamalıyız.</p>
			<p>6- Zina, livata (eşcinsel ilişki), hırsızlık, gasb (silahlı soygun) yapmamalı, içki içmemeli, kumar oynamamalıyız.</p>
			<p>8- İftira (gerçek olmayan suçlama, aşağılama, ayıplama vb) etmemeli, özellikle masum bir insana  zina iftirasında bulunmamalıyız.</p>
			<p>9- Yalan yere şahitlik yapmamalı, rüşvet alıp - vermemeliyiz.</p>
			<p>10- Büyücü, falcı, medyum, kahin vb gibi insanlara gitmemeli, bunların yaptıkları şeytani fiillerden uzak durmalıyız.</p>
			<p>11- Üzerine Allah'ın adı anılmadan kesilen hayvanların etini, necis sürüngenleri ve böcekleri, domuz eti, kan yememeliyiz.</p>
			<p>12- Borca, emanete emin ve güvenilir olmalı, zamanında sahibine teslim etmeliyiz.</p>
			<p>13- Gıybet (dedikodu) etmemeli ve laf taşımamalıyız. Lanet etmemeli, küfürlü konuşmamalıyız.</p>
			<p>14- Başka insanların mahremiyetini (gizlisini) araştırmamalı ve zan ile (delilsiz, şahitsiz, hissi veya duygusal)  konuşmamalıyız. Şeref, haysiyet ve namusuna kötü  söz söylememeliyiz.</p>
			<p>15- Ölçü ve tartıda hile yapmamalı ve asla aldatmamalıyız.</p>
			<p>16- Gayri meşru yol, yöntem ve mesleklerle hayatımızı kazanarak haram rızık yememeliyiz.</p>
			<p><u>Bu yasaklardan kaçındığımız gibi Allah'ın rahmet ve hıfzına (koruma) layık olabilmek içinde kullarına emrettiği farzları ve salih amelleri öğrenip, ölünceye kadar terketmemeliyiz. Özellikle  hem dünya hem de ahiret menfaatini kazanabilmek için ibadetleri mutlaka eda etmeliyiz. </u></p>
			<p>1- Allah'ın kitap-peygamber ile bildirdiklerine şeksiz şüphesiz iman etmeliyiz. <u>La İlahe İllallah Muhammed ür Resulullah</u> kelimeyi şehadetini, kalbimiz, dilimiz ile ihlasla zikretmeliyiz. Allah'ın isim ve sıfatlarını öğrenmeliyiz. Sadece Allah'a iman ve ibadet etmeli, sadece ondan istemeliyiz.</p>
			<p>2-  İbadet, imanın fiile dönüşmesidir. Özellikle beş vakit farz namaz ile hem imanımızı tezahür ettirir, hem de  Allah'ın yardımıyla imanımızı koruruz. Namaz dinin direğidir, namaz zırh gibi insanı kötü işler ve edebsizlikten korur.  Namazı terkeden dinini yıkar, Allah'ın muhafazası dışına çıkar ve nefsinin kötü ve aşırı arzularının, akabinde şeytanın tesirine girer. Şeytan edepsizliği ve kötülüğü emreder, namaz ise insanı korur.</p>
			<p>3- Farz olan ramazan orucu nefsimizi terbiye eder. Terbiye edilen nefis kanaat etmesini öğrenir. Heva ve hevesin aşırı isteklerine karşı dirayetli olur. Oruç şeytanın nefsi azdırıp sapkınlığa doğru sürüklemesini frenler. Merhamet duygularını artırır, bencillik ve kibirden muhafaza ederek şeytanın kullandığı nefsin zaaflarını kontrol altında tutar. Şeytan musallatının en tehlikeli oyunu insan bedenini nefsin aşırı arzularına mübtela etmektir. </p>
			<p>4- Zekat ve sadaka mal ile yapılan ibadettir. İnsanı cimrilikten korur, cömert yapar. Malı temizler. Helal kazanmayı sağlar. Helal ve temiz mal insanın aşırıya kaçmasını ve şeytanın musallatını engeller. Haram kazanılmış mal nefsin aşırı arzularını kamçılar ve sahibinin diğer günahlara (kumar, zina, içki vb) girmesini kolaylaştırır. Zekat ve sadaka insanın mala tapmasını önler, emanetçi olduğunu hatırlatır. Muhtaçların ihtiyaçlarını giderme fiili ile Allah'ın Rahman, Rezzak, Kerim,  gibi isimlerinin tecellesine mazhar eder. Karun’laşmasını ve sonunda helak olmasını önler.</p>
			<p>5- Maddi imkan olduğunda yapılabilirse, Hacc ve Umre ibadeti ise;  Allah'ın rahmetinin açıkça hissedilir şekilde tecelli ettiği ve resulünün yaşayıp meftun olduğu topraklarda, insanı dünya sevgisinden uzaklaştırır. Dünyanın fani olduğunu gösterir, mahşer provası ile ahiret inancını artırır ve günahlardan tevbe istiğfar ile Rabb’ine dönmesine sebep olur. Dünyanın boş ve anlamsız olduğunu öğretir. Ahirete yönelmesini, vazifelerini daha şuurlU yapmasını, böylece şeytana karşı daha iradeli ve güçlü olmasını sağlar.</p>
			<p>6- Kalpler ancak Allah'ın zikri ile mutmain (tatmin)olur. Ruh Rabb'imizin kendisinden bize bahşettiği bir varlıktır. İbadet ve zikir ile onu bağlı kaldığında gurbette sılasıyla irtibatı olup, mutlaka bir gün oraya döneceği ümidiyle sabır ve tahammül eden bir gurbetçi gibi metin olur. Özü, kaynağı ve döneceği yer O'dur. Ruhumuzu nefsin eline ve şeytanın musallatına teslim edersek, çölde aç, susuz ve yolunu kaybetmiş bir yolcuya döner ve helak oluruz. Bu dünya çölünde  doğru yolu bulabilmemiz için ruhumuzu özü, kaynağı ile irtibatlı, rabıtalı tutmak gerekir. Bu rabıtayı sağlayan zikir, kulunun Rabb'ine sürekli olarak iman ve itaatinin ilanı olup, onun Rahman ve Rahim sıfatlarına iltica etmektir. Ona güvenmek, ihtiyacını ondan dilemek ve kulunu dünya ve ahirette korumasını istemektir. Çalışırken veya boş vakitlerimizde özellikle Kelime-i Tevhid olan La İlahe İllallah zikrini dilimizden eksik etmeyelim. Zikreden ruh ve beden Allah'ın muhafazası altında şuurlu olup, musallata karşı korunur. Ayrıca bilerek veya bilmeyerek işlediğimiz günahlarımız için yine dilimizden ve dualarımızdan tevbe ve istiğfarı eksik etmeyelim. Rabb'imiz Kur'anda şöyle bildiriyor; “Siz şükreder ve iman ederseniz Allah size  azabı ne yapar? Allah şükredenlerin mükafatını veren ve herşeyi bilendir." Yine zatının dünya ve ahirette mü'minlerin velisi olduğunu onlara merhamet nazarıyla muamele edeceğini bildiriyor.</p>
			<p>Kardeşim ister kabul et, ister etme; Allah Kur'an-ı Kerim’de imtihan hakikatine istinaden inanç yönüyle dünyada iki yol yarattım. Biri hak yol olan sırat-i müstakim, yani İslam dini. Diğeri ise batıl olan şeytanın yolu ve dini. Cinleri ve insanları hak yol üzere, ancak bana kulluk etsinler diye yarattım, diye bildiriyor. </p>
			<p>Fakat kendi rızaları ile gönülden iman eden muhlis kullarını seçmek için, cinin ve insanın iradesini serbest bırakmış. Elçileri ve gönderdiği ilahi kitaplar ile bu imtihan gerçeğini kullarına bildirmiş. Yollardan hangisini tercih edeceğinde cini ve insanı özgür bırakmış. Fakat Hakk yolu seçeni kendisine kul olarak kabul edip, dünyada onu şeytandan koruyup, ahirette cennet ile mükafatlandıracağını kendisine söz vermiş. Nefsinin kötü arzularına uyarak  ahireti inkar eden ve şeytanın musallat olmasıyla, kendi iradesiyle onun yoluna giden cinler ve insanları ise inkar ve günahlarından dolayı  cehenneme doldurmakla tehdit ediyor. </p>
			<p>İblis ve şeytanları bu hakikati çok iyi biliyor ve özellikle insanları kendi yollarına çekebilmek, ya da dünya hayatında da onları zor durumlara düşürerek mutsuz etmek için sürekli insanlarla uğraşıyor. Musallatın en hafifi insanın kutsallara olan ilgisizliği veya inançsızlığı ve bunun sonucunda ortaya çıkan nefsi yaşam şeklidir. Bu tür insanlarda daha sonra Nevrotik rahatsızlıklarda denilen sıkıntılar yaşanarak, özel ve aile hayatı bozulur. Musallatın en kötüsü ise bilinç istilası, yani işgali ile insan benliğin devre dışı bırakılmasıdır. Bu safhada gerçeklikten kopma, cinnet geçirme nöbetleri, çıldırma, delirmeler yaşanır. Neticede facia denilecek olaylar meydana gelir. </p>
			<p>İşte dünya hayatının hakikati; insan asla özgür değildir. Ya Allah'a kul olarak insan onuruna yakışır bir dünya hayatı yaşayıp, cennet ile müjdelenip gerçek özgürlüğü orada elde etme veya nefsi yaşamı özgürlük zannederek heva ve hevesinin esiri olup ve akabinde de şeytanın musallatı ile ona kul olarak dünya ve ahiretini kaybetme imtihanına tabi tutulmuştur.</p> 
			<p>Bu satırları okuyan kardeşlerime tavsiyem kendilerine Türkçe açıklamalı bir Kur'an-ı Kerim alsınlar ve hakikati oradan kendileri öğrensinler. Çünkü mahşer sorgusunda Kur’an'dan sorumlu tutulacağız. Kur'an bizim için gönderilmiş uyarıcı, müjdeleyici ilahi  rehber bir kitapdır. Kur'an-ı Kerim hem mü'minlere rahmet, hem de  sinelerde olana (ruha-kalbe) şifadır. Eğer kendimize müslüman diyorsak, dinimizin kutsal kitabını mutlaka okumalı ve hakikati kendimiz öğrenmeliyiz. Biz sadece bu konudaki bilgi ve tecrübelerimizi hizmet mantığıyla sizlere aktarıyoruz.</p> 
			<p>İşte hakikat budur, şeytandan korunmak istiyorsak Hakk’ı tercih etmeliyiz. Yoksa  Allah’tan başka kimse bizi koruyamaz. İblis ve şeytanları ruhumuzu ele geçirmek konusunda çok bilgili, tecrübeli ve hilecidir. Özgür irademizle yaşadığımızı zannederiz, ama Hakk’ı terkedip nefsi yaşamakla alternatifsiz onun boyunduruğuna gireriz, bunu anlayamayız bile. Onu somut olarak göremediğimizden, asla onun varlığına da inanmak istemeyiz. Bu onun en büyük hilesidir. Ele geçirdiği insana dayanaksız çeşitli fikir ve ideolojiler ile kendini inkar ettirmek.....</p>
			<p>YA HAFİZ ÜL ALİM ÜL KADİR-İ YA ALLAH İHFAZNA, FALLAHÜ HAYRÜN HAFİZEN HÜVE ERHAMÜRRAHİMİN. AMİN</p>


		</div>
	</div>
</div>