<!-- FA Questions Text -->
<div id="js__scroll-to-section" class="g-container--md g-padding-y-80--xs g-padding-y-125--sm">
	<h3 id="textHead" class="g-font-size-32--xs g-font-size-36--md g-text-center--xs g-margin-b-80--xs">
		MUSALLAT İLE OLUŞAN YAYGIN RUHSAL RAHATSIZLIKLAR
	</h3>

	<div class="g-text-left--xs">
		<div>
			<p align="justify">Cin ve büyü musallatı ile hastalarda ortaya çıkan ve içten gelen bazı ruhsal sıkıntılar ve rahatsızlıklar vardır. Bu bölümde bunlara yer verilerek açıklanacaktır.</p><p  
			align="justify">&nbsp&nbsp&nbsp&nbsp&nbsp VEHİM: Kaynağı belli olmayan, belirsiz, manasız korkudur. Kötü bir ruhsal hastalıktır. Kişi vehim hastalığına tutulursa ondan kurtulması zor olur. İnsan hayatında bazı vehimler eksik değildir. Bazı kişilerin hayatı tamamen vehim içinde geçer.  Vehim ortaya çıkmasında dış faktörlerin etkisiyle yanında insanların, cin ve şeytanlardan korkmalarının da büyük bir rolü vardır. Şeytanlar somut olayların etkisiyle oluşan vehmi daha da kuvvetlendirip aşırılaştırır. Aslında insan vehim hastalığına yakalanırsa bu cin ve büyü musallatıyla oluşan hastalıklardan daha tehlikeli olur. Çünkü cin çarpması Allah'ın lütfu ile Kur'an-ı Kerim rukyesi ile (Kur'an'dan okunan ayet ve dualar) ortadan kalkar. Ama vehim hastası bitip tükenmeyen bir anafor, döngü içindedir. Bazı kimseler aslında kendisinde bir musallat olmadığı halde, vehme kapılarak büyülü olduğunu veya falancanın aralarında bir meseleden dolayı kendisine büyü yaptırdığını zanneder. Böylece onda hayali bir kuşku-korku ile oluşan vehim nedeniyle,  zihni bulanır ve hayatı alt üst olur. Sonrada kendi kendine büyülü olduğunu telkin eder. Veya,  paranoid düşünce ve duygular ile bilincini dış dünya ya ait olaylar ile sürekli meşgul eden insanlarda vehim hiç eksik olmaz. Böyle durumlarda hormon salgılayan bezler iyi çalışmazlar artık onda çarpılma ve büyülenme belirtileri  görülür, kasılma ve bayılmalar ortaya çıkar. Bundan sonra hayatına aşırı korku ile stres girer. Sinir ve sindirim sistemi bozulur. Vücutta bazı organik hastalık belirtileri ortaya çıkar. Hasta kalp bölgesinde ağrı hisseder. Sinir sisteminin bozulması sonucu başka rahatsızlık belirtileri de ortaya çıkar. İnsan vücudundaki her organ stres halinden etkilenir. Kalp atışları artar, tansiyon  yükselir. Sindirim sisteminin bozulmasıyla karın ağrıları ortaya çıkar. Hastanın cinsel hayatı bozulur. Baş bölgesinde kas gerilmesi olur, yarım baş ağrısı ortaya çıkar. </p><p 
			align="justify">&nbsp&nbsp&nbsp&nbsp&nbsp Gerçek şudur ki; kendisinde musallat olduğunu zanneden ve Kur'an'la tedavi olmak isteyenlerin büyük bir kısmı vehim hastasıdır. Yani aslında gerçek olmayan cin veya büyü musallatı korkusudur. Bu korku onları stres ve depresyona sokar. Musallat belirtileri gösterselerde cin çarpmasına uğrayanlar pek azdır. Psikiyatrinin vurguladığı gerçek şudur; Somut veya soyut sebepler ile ortaya çıkan korku ve kaygı nedeniyle devamlı stresli bulunmak, gerçek organ hastalıklarına da sebep olur. Stres deri, mide, barsak, göğüs anjini vb başka rahatsızlıkları ortaya çıkarır. Artık hastanın hayat tarzı değişir, arzu ve umutları kalmaz, işini ihmal eder, evlilik hayatı bozulur. Sonunda vehmin, kaygı-korkunun esiri olur. Ayrıca vehimleri nedeniyle bu tür hastalarda zorlantılı davranışlar yani takıntılar da oluşmaktadır. </p><p 
			align="justify">&nbsp&nbsp&nbsp&nbsp&nbsp SARA: Sara, hastada şuur kaybıyla birlikte hastaya aniden ve zaman zaman gelen kasılma ve titreme halidir. Saranın organik ve ruhsal sebepleri vardır. Ancak saranın sebepleri arasında önemli birisi daha vardır ki, cin çarpması sebebiyle olanıdır. Modern tıbbın sebebini açıklayamadığı sara çeşidi bu şekilde olanıdır. Bu durum, dıştaki  şuurlu bir habis varlığın (cin) hastanın beynini ve bedenini etkileyen olağanüstü bir tesiridir. Sara hastalığının ortaya çıkmasında cin musallatını inkar etmek mümkün değildir. Eskiden sara hastalığının, dışarıdan güçlü bir sebeple oluştuğuna inanıldığından, sara hastalığına Rabbani ve kutsal hastalık adı verilirdi. Eskiler, bu hastalığın ani ve şiddetli görüntülerinin, vücuda giren ve beyne giden kötü ruhların etkisi ile meydana geldiği yorumunu yapmışlardır. Cin çarpması sebebi ile oluşan saranın, Kur'an-ı Kerim'le tedavisi yapılabilmektedir. </p><p 
			align="justify">&nbsp&nbsp&nbsp&nbsp&nbsp DEPRESYON: Maddi-manevi çöküntü, iç sıkıntısı, aşırı üzüntü demektir. Günümüzün en yaygın hastalıklarından biridir. Depresyonun belirtileri; Sıkıntı ve üzüntü duyma, yemeğe karşı isteksizlik, iştah kaybı, kendini toplayamama unutkanlık, uyku bozukluğu kilo kaybı, cinsel isteksizlik. Depresyonun pek çok dış (hayat, aile, iş ortamı, çevre vb..)  ve iç sebebi (beyin ve hormon faaliyetlerinin bozulması) vardır. Esas itibariyle depresyon ruhsal hastalıklardandır. Kalıcı tedavisi Kur'ana ve sünnete uygun hayat tarzıdır. Hastanın sıkıntısını almak için rukye okunur, dini telkinde bulunulur. Hastada açık somut bir tıbbi sebep ortaya çıkmamış ve depresyon cin çarpmasının belirtilerinden biri ise,  rukye uygulamada bir sakınca ortaya çıkmaz. Çünkü, Kur'anla tedavi ile psikiyatri arasında bir çelişki yoktur.</p><p 
			align="justify">&nbsp&nbsp&nbsp&nbsp&nbsp STRESS: Gergin olma ve korku-kaygı halinde bulunmadır. Stres, sukunet ve huzurun tersidir. Stresin süresi uzadıkça müzmin hale gelir ve yorgunluk belirtileri artar. Kalp hastalığı, tansiyon, mide ve bağırsak ülseri, kolit vb. birçok organik hastalıklar ortaya çıkar. Stresin en önemli sebepleri şunlardır; Korku ve endişe içinde olmak, bilinen ve bilinmeyen şeylerden kötülük beklemek, insanın eğilimleri ile bunlara engel olan şart ve kayıtlar arasında mücadele etmesi (nevroz), zihni ve bedeni yorgunluk. Stresin de tedavisinde rukye ve telkin faydalı olmaktadır. </p><p 
			align="justify">&nbsp&nbsp&nbsp&nbsp&nbsp Vehim, vesvese, stres ve depresyon gibi ruhsal rahatsızlıkların dış dünya ile ilgili sebepleri yoksa mutlaka içsel-ruhsal sebepler ile ilgilidir. Bu rahatsızlıkların içsel sebebi ruha musallatın olması ve ruhsal dengenin bozulmasıdır. Gerek doğrudan, gerekse büyü ile musallat olan cinlerin hastalardaki en etkili faaliyetleri, bu rahatsızlıkları ortaya çıkararak onların ruhlarını baskı altına almaktır. Hastanın akıl melekelerini zayıflatıp, hatta bozarak, hastaları tesir altına alıp, yönetmek için onları kendi iradelerine tabi kılarak istedikleri fiilleri yaptırtmaktır. Stres ve depresyon hastanın dış dünya ile ilişkisini azaltıp içe kapanmasını sağlar ve diğer insanlardan uzaklaştırır. Böylece hasta içteki şeytanın telkinlerine daha fazla kulak verir. Onun etki alanına girer. Şeytan vehim ve vesvese  ile hastaların iradesini zayıflatıp, mücadele gücünü azaltır ve doğru olanı yapmasında tereddüt meydana  getirir. Hastanın  kendine olan güveni ve inancı zayıflar. Telkine açık hale gelir. Şeytanında zaten istediği budur. Vehim ve vesveseye tutulmuş hastaya kendi fikirlerini alternatif olarak sunar ve bunları davranışa dönüştürmesinde ısrar eder, fikirlerini güçlendirmek ve sonuç elde etmek için de hastaya duygusal baskıda bulunur. Tabi ki, bütün bunlar insanın iç dünyasında (ruhunda-beyninde) meydana gelir. Hasta insan, bu sıkıntıları beyninde kendisine düşman olan bir varlığın meydana getirdiğini bilmez, kendinden zanneder, tercihlerinin yanlış  olduğunun farkına da varamaz. Ama hastaya yakın olan insanlar, hastadaki yanlış düşünce, fikir, söylem ve eylemleri görünce onun ruh sağlığını kaybettiğini anlar. Bu durum bir hayli vakit aldığından hastalık ilerler ve tedavisi gittikçe zorlaşır. </p><p 
			align="justify">&nbsp&nbsp&nbsp&nbsp&nbsp Bu sıkıntıları aşmanın tek yolu, hastanın vücuduna ve özellikle de beynine  yerleşmiş şeytani enerjinin hastadan çıkarılmasıdır. Çünkü cinler bu enerji ile hastanın ruhsal yapısını bozarak adı geçen rahatsızlıkları ortaya çıkarmaktadırlar. Hastalıkların kaynağı hastadaki şeytani enerjidir. Diğer tabirle, cinin insana teması yani insanın içine girerek onu çarpmasıdır. Bu enerjinin hastadan uzaklaştırılması için imanı kamil, takvalı ehil bir insanın hastanın başına rukye yapması gerekir. Yani ona dua ve Kur'an okuyarak Allah'tan şifa vermesi için yardım istemelidir. Rukye okunurken okuyanda oluşan rahmani enerji, hastanın başına geçerek oradaki şeytani enerjiyi kovmakta ve onun yerini almaktadır. Böylece hasta inşallah şifaya kavuşmaktadır.</p>
		</div>
	</div>
</div>
<!-- End FA Questions Text -->